# -*- coding: utf-8 -*-
"""python_code_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16oAvNrkMjZlZfqtLjZYmUikcfQYTFOhn
"""

n = 20
num1 = 0
num2 = 1
next_number = num2
count = 1

while count <= n:
    print(next_number, end=" ")
    count += 1
    num1, num2 = num2, next_number
    next_number = num1 + num2
print()